import{Capacitor}from'@capacitor/core';
import{Directory,Filesystem}from'@capacitor/filesystem';
const DB_NAME='byd-skyrail-local-files',STORE='files',ROOT='skyrail/documents',OPFS_ROOT='byd-skyrail/documents';
const safe=v=>String(v??'').replace(/[^a-zA-Z0-9._-]/g,'_');
const bytesToBase64=bytes=>{let binary='';for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(binary)};
const base64ToBlob=(base64,type='application/pdf')=>{const binary=atob(base64),bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);return new Blob([bytes],{type})};
const canOpfs=()=>typeof navigator!=='undefined'&&typeof navigator.storage?.getDirectory==='function';
function openWebDb(){return new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,1);req.onupgradeneeded=()=>{if(!req.result.objectStoreNames.contains(STORE))req.result.createObjectStore(STORE,{keyPath:'id'})};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function webTx(mode,fn){const db=await openWebDb();try{return await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,mode),store=tx.objectStore(STORE);let value;Promise.resolve(fn(store)).then(v=>value=v).catch(error=>{try{tx.abort()}catch{}reject(error)});tx.oncomplete=()=>resolve(value);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error('Transação IndexedDB abortada.'))})}finally{db.close()}}
async function row(id){return webTx('readonly',store=>new Promise((resolve,reject)=>{const r=store.get(String(id));r.onsuccess=()=>resolve(r.result||null);r.onerror=()=>reject(r.error)}))}
async function root(){if(!canOpfs())throw new Error('Armazenamento streaming indisponível.');return navigator.storage.getDirectory()}
async function opfsFile(path,{create=false}={}){const parts=String(path||'').split('/').filter(Boolean);if(!parts.length)throw new Error('Caminho OPFS inválido.');let dir=await root();for(const part of parts.slice(0,-1))dir=await dir.getDirectoryHandle(safe(part),{create});return dir.getFileHandle(safe(parts.at(-1)),{create})}
async function removeOpfs(path){if(!path||!canOpfs())return;const parts=String(path).split('/').filter(Boolean);if(!parts.length)return;try{let dir=await root();for(const part of parts.slice(0,-1))dir=await dir.getDirectoryHandle(safe(part));await dir.removeEntry(safe(parts.at(-1)))}catch{}}
async function clearOpfs(){if(!canOpfs())return;try{await(await root()).removeEntry('byd-skyrail',{recursive:true})}catch{}}
const idsOf=(records=[],removeIds=[])=>[...new Set([...records.map(r=>String(r.id)),...removeIds.map(String)])];
export class DocumentFileService{
 isNative(){return Capacitor.isNativePlatform()}
 supportsStreamingWeb(){return!this.isNative()&&canOpfs()}
 pathFor(document){const file=safe(document.file_path||document.file||`${document.id}.pdf`);return`${ROOT}/${safe(document.id)}/${file}`}
 async has(document){if(this.isNative()){try{await Filesystem.stat({path:this.pathFor(document),directory:Directory.Data});return true}catch{return false}}return!!(await webTx('readonly',store=>new Promise((resolve,reject)=>{const r=store.getKey(document.id);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})))}
 async availableIds(documents=[]){const wanted=new Set(documents.map(d=>String(d?.id||'')).filter(Boolean));if(!wanted.size)return new Set();if(this.isNative()){const rows=await Promise.all(documents.map(async d=>[String(d.id),await this.has(d)]));return new Set(rows.filter(([,ok])=>ok).map(([id])=>id))}const keys=await webTx('readonly',store=>new Promise((resolve,reject)=>{const r=store.getAllKeys();r.onsuccess=()=>resolve(r.result||[]);r.onerror=()=>reject(r.error)}));return new Set(keys.map(String).filter(id=>wanted.has(id)))}
 async putBytes(document,bytes){if(!(bytes instanceof Uint8Array))bytes=new Uint8Array(bytes);if(this.isNative()){const dir=`${ROOT}/${safe(document.id)}`;await Filesystem.mkdir({path:dir,directory:Directory.Data,recursive:true});await Filesystem.writeFile({path:this.pathFor(document),directory:Directory.Data,data:bytesToBase64(bytes),recursive:true});return}const blob=new Blob([bytes],{type:'application/pdf'});await webTx('readwrite',store=>new Promise((resolve,reject)=>{const r=store.put({id:String(document.id),blob,file_path:document.file_path||document.file});r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error)}))}
 async createStreamWriter(document,physicalName,{maxBufferedBytes=32*1024*1024}={}){
  if(this.supportsStreamingWeb()){
   const opfs_path=`${OPFS_ROOT}/${safe(document.id)}/${safe(physicalName)}`,handle=await opfsFile(opfs_path,{create:true}),writable=await handle.createWritable({keepExistingData:false});let chain=Promise.resolve(),failure=null,closed=false;const record={id:String(document.id),storage:'opfs',opfs_path,file_path:String(physicalName||'')};
   return{record,write(data){if(failure||closed)return;const chunk=data.slice();chain=chain.then(()=>writable.write(chunk)).catch(error=>failure=error)},async drain(){await chain;if(failure)throw failure},async close(){if(closed)return record;await chain;if(failure)throw failure;await writable.close();closed=true;return record},async abort(){if(!closed){try{await writable.abort()}catch{}closed=true}await removeOpfs(opfs_path)}};
  }
  let chunks=[],total=0,closed=false;return{write(data){if(closed)throw new Error('Writer já finalizado.');const copy=data.slice();total+=copy.length;if(total>maxBufferedBytes)throw new Error('PDF grande demais para o fallback em memória deste navegador. Use armazenamento streaming ou o app Android.');chunks.push(copy)},async drain(){},async close(){if(closed)throw new Error('Writer já finalizado.');closed=true;const record={id:String(document.id),storage:'indexeddb',blob:new Blob(chunks,{type:'application/pdf'}),file_path:String(physicalName||'')};chunks=[];return record},async abort(){closed=true;chunks=[]}};
 }
 async getRecord(id){return this.isNative()?null:row(id)}
 async commitPreparedRecords({records=[],removeIds=[]}={}){if(this.isNative())throw new Error('Operação exclusiva do fallback web.');const ids=idsOf(records,removeIds),snapshot=new Map();for(const id of ids)snapshot.set(id,await row(id));const recordIds=new Set(records.map(r=>String(r.id)));await webTx('readwrite',store=>Promise.all([...records.map(item=>new Promise((resolve,reject)=>{const r=store.put(item);r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error)})),...removeIds.filter(id=>!recordIds.has(String(id))).map(id=>new Promise((resolve,reject)=>{const r=store.delete(String(id));r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error)}))]));return snapshot}
 async rollbackPreparedRecords({records=[],removeIds=[],snapshot=new Map()}={}){if(this.isNative())return;const ids=idsOf(records,removeIds);await webTx('readwrite',store=>Promise.all(ids.map(id=>new Promise((resolve,reject)=>{const previous=snapshot.get(String(id)),r=previous?store.put(previous):store.delete(String(id));r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error)}))));for(const item of records){const previous=snapshot.get(String(item.id));if(item.opfs_path&&item.opfs_path!==previous?.opfs_path)await removeOpfs(item.opfs_path)}}
 async finalizePreparedRecords({records=[],removeIds=[],snapshot=new Map()}={}){if(this.isNative())return;const next=new Map(records.map(r=>[String(r.id),r]));for(const id of idsOf(records,removeIds)){const previous=snapshot.get(String(id)),current=next.get(String(id));if(previous?.opfs_path&&previous.opfs_path!==current?.opfs_path)await removeOpfs(previous.opfs_path)}}
 async discardPreparedRecords(records=[]){if(this.isNative())return;for(const item of records)if(item?.opfs_path)await removeOpfs(item.opfs_path)}
 async getViewerSource(document){if(this.isNative()){try{const result=await Filesystem.getUri({path:this.pathFor(document),directory:Directory.Data});return{url:Capacitor.convertFileSrc(result.uri),blob:null}}catch{return null}}const blob=await this.getBlob(document);return blob?{url:null,blob}:null}
 async getBlob(document){if(this.isNative()){try{const result=await Filesystem.readFile({path:this.pathFor(document),directory:Directory.Data});return base64ToBlob(String(result.data))}catch{return null}}const item=await row(document.id);if(item?.opfs_path){try{return await(await opfsFile(item.opfs_path)).getFile()}catch{return null}}return item?.blob instanceof Blob?item.blob:null}
 async remove(document){if(this.isNative()){try{await Filesystem.deleteFile({path:this.pathFor(document),directory:Directory.Data})}catch{}return}const item=await row(document.id);await webTx('readwrite',store=>new Promise((resolve,reject)=>{const r=store.delete(String(document.id));r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error)}));if(item?.opfs_path)await removeOpfs(item.opfs_path)}
 async removeAll(){if(this.isNative()){try{await Filesystem.rmdir({path:ROOT,directory:Directory.Data,recursive:true})}catch{}return}await webTx('readwrite',store=>new Promise((resolve,reject)=>{const r=store.clear();r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error)}));await clearOpfs()}
}
export const documentFileService=new DocumentFileService();
