import{getClient}from'./client.js';import{normalizeDocument,sortDocuments}from'./model.js';
export const BUCKET='documents';const COLS='id,code,title,discipline,revision,file_path,updated_at,active';const v=x=>String(x??'').trim();
export async function currentMember(){const c=getClient();const{data:{session}}=await c.auth.getSession();if(!session?.user)return null;const{data,error}=await c.from('members').select('user_id,display_name,role,active').eq('user_id',session.user.id).single();if(error||!data?.active)return null;return{user:session.user,...data}}
export async function signIn(email,password){const{error}=await getClient().auth.signInWithPassword({email:v(email),password:String(password??'')});if(error)throw new Error('E-mail ou senha inválidos.');return currentMember()}
export async function signOut(){await getClient().auth.signOut({scope:'local'})}
export async function listActive(){const{data,error}=await getClient().from('documents').select(COLS).eq('active',true).order('discipline').order('code');if(error)throw new Error('Não foi possível carregar a biblioteca.');return sortDocuments((data||[]).map(normalizeDocument).filter(Boolean))}
export async function listAdmin(){const{data,error}=await getClient().from('documents').select(COLS).order('discipline').order('code');if(error)throw new Error('Não foi possível carregar a administração.');return sortDocuments((data||[]).map(normalizeDocument).filter(Boolean))}
export async function downloadPdf(path){const{data,error}=await getClient().storage.from(BUCKET).download(path);if(error||!(data instanceof Blob))throw new Error('Não foi possível baixar o PDF.');return data}
function payload(i){const p={code:v(i.code),title:v(i.title),discipline:v(i.discipline),revision:v(i.revision),active:i.active!==false};for(const[k,val]of Object.entries(p))if(k!=='active'&&!val)throw new Error(`Campo ${k} obrigatório.`);return p}
function pdf(file,required){if(!file&&!required)return null;if(!(file instanceof File)||file.size<1||!/\.pdf$/i.test(file.name))throw new Error('Selecione um PDF válido.');return file}
async function upload(id,file){const path=`${id}/${crypto.randomUUID()}.pdf`;const{error}=await getClient().storage.from(BUCKET).upload(path,file,{contentType:'application/pdf',cacheControl:'0',upsert:false});if(error)throw new Error('Não foi possível enviar o PDF.');return path}
async function remove(path){if(path)await getClient().storage.from(BUCKET).remove([path]).catch(()=>{})}
async function findByCode(code){const{data,error}=await getClient().from('documents').select(COLS).eq('code',v(code)).maybeSingle();if(error)throw new Error('Não foi possível verificar o código do documento.');return normalizeDocument(data)}
export async function saveDocument(existing,input){const p=payload(input);const current=existing||await findByCode(p.code);const f=pdf(input.file,!current);const id=current?.id||crypto.randomUUID();const old=current?.file_path||'';const next=f?await upload(id,f):old;const c=getClient();let q;if(current)q=c.from('documents').update({...p,file_path:next,updated_at:new Date().toISOString()}).eq('id',id);else q=c.from('documents').insert({id,...p,file_path:next,updated_at:new Date().toISOString()});const{data,error}=await q.select(COLS).single();if(error||!data){if(f)await remove(next);throw new Error('Não foi possível salvar o documento.');}if(f&&old&&old!==next)await remove(old);return normalizeDocument(data)}
