const CODE_RE=/\bPW(?:[\s._\-/]*[A-Z0-9])(?:[A-Z0-9._\-/]*[A-Z0-9])?\b/gi;
const REV_LABEL_RE=/(?:REV(?:ISÃO|ISAO|ISION)?\.?|REVISÃO|REVISION)\s*[:\-]?\s*([A-Z0-9]{1,4})\b/i;
const DESC_LABEL_RE=/(?:DESCRIÇÃO|DESCRICAO|DESCRIPTION|T[IÍ]TULO|TITLE)\s*[:\-]?\s*(.{5,180})/i;
const MIN_TEXT_CHARS=80;
const AUTO_THRESHOLD=.82;
const clean=v=>String(v??'').replace(/\s+/g,' ').trim();
function groupLines(items){const rows=[];for(const item of items){const str=clean(item.str);if(!str)continue;const x=Number(item.transform?.[4]||0),y=Number(item.transform?.[5]||0);let row=rows.find(r=>Math.abs(r.y-y)<=3);if(!row){row={y,items:[]};rows.push(row)}row.items.push({x,str})}return rows.sort((a,b)=>b.y-a.y).map(r=>r.items.sort((a,b)=>a.x-b.x).map(i=>i.str).join(' '))}
function candidateCode(text){const values=[...text.matchAll(CODE_RE)].map(m=>clean(m[0]).replace(/\s+/g,''));const unique=[...new Set(values)];if(!unique.length)return{value:'',confidence:0,ambiguous:false};return{value:unique[0],confidence:unique.length===1?.94:.68,ambiguous:unique.length>1,candidates:unique}}
function candidateRevision(text,lines=[]){const direct=text.match(REV_LABEL_RE);if(direct)return{value:clean(direct[1]).toUpperCase(),confidence:.95,ambiguous:false};const hits=[];for(let i=0;i<lines.length;i++){if(/\bREV(?:ISÃO|ISAO|ISION)?\b/i.test(lines[i])){const same=lines[i].match(/\b(?:REV(?:ISÃO|ISAO|ISION)?\.?|REVISÃO|REVISION)\s*[:\-]?\s*([A-Z0-9]{1,4})\b/i);if(same)hits.push(same[1]);else if(lines[i+1]&&/^[A-Z0-9]{1,4}$/.test(clean(lines[i+1])))hits.push(clean(lines[i+1]))}}const unique=[...new Set(hits.map(v=>v.toUpperCase()))];return unique.length?{value:unique[0],confidence:unique.length===1?.84:.58,ambiguous:unique.length>1,candidates:unique}:{value:'',confidence:0,ambiguous:false}}
function candidateDescription(text,lines=[]){const direct=text.match(DESC_LABEL_RE);if(direct)return{value:clean(direct[1]).slice(0,240),confidence:.9,ambiguous:false};for(let i=0;i<lines.length;i++){if(/^(DESCRIÇÃO|DESCRICAO|DESCRIPTION|T[IÍ]TULO|TITLE)\b/i.test(clean(lines[i]))){const next=clean(lines[i+1]);if(next&&next.length>=5)return{value:next.slice(0,240),confidence:.78,ambiguous:false}}}return{value:'',confidence:0,ambiguous:false}}
export function parseExtractedText(text,lines=[]){const normalized=String(text||'').replace(/\u0000/g,' ');return{code:candidateCode(normalized),title:candidateDescription(normalized,lines),revision:candidateRevision(normalized,lines)}}
function mergeField(primary,fallback){if(primary?.value&&primary.confidence>=fallback?.confidence)return primary;return fallback?.value?fallback:primary}
function resultFrom(fields,source){const issues=[];for(const[key,label]of[['code','Código PW'],['title','Descrição'],['revision','Revisão']]){const f=fields[key];if(!f?.value)issues.push(`${label} não identificado.`);else if(f.ambiguous)issues.push(`${label} possui mais de um candidato.`);else if(f.confidence<AUTO_THRESHOLD)issues.push(`${label} com baixa confiança.`)}return{extracted:{code:fields.code?.value||'',title:fields.title?.value||'',revision:fields.revision?.value||''},confidence:{code:fields.code?.confidence||0,title:fields.title?.confidence||0,revision:fields.revision?.confidence||0},candidates:{code:fields.code?.candidates||[],title:fields.title?.candidates||[],revision:fields.revision?.candidates||[]},issues,source,status:issues.length?'review':'ready'}}
async function textFromPdf(file,onProgress){if(!globalThis.pdfjsLib)throw new Error('PDF.js não carregado.');if(!pdfjsLib.GlobalWorkerOptions.workerSrc)pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';const pdf=await pdfjsLib.getDocument({data:await file.arrayBuffer()}).promise;const pages=Math.min(pdf.numPages,3),allLines=[];for(let n=1;n<=pages;n++){onProgress?.({stage:'text',page:n,total:pages});const page=await pdf.getPage(n),content=await page.getTextContent(),lines=groupLines(content.items||[]);allLines.push(...lines)}return{pdf,text:allLines.join('\n'),lines:allLines}}
async function renderPageCanvas(pdf,pageNumber=1,scale=1.8){const page=await pdf.getPage(pageNumber),viewport=page.getViewport({scale});const canvas=document.createElement('canvas');canvas.width=Math.ceil(viewport.width);canvas.height=Math.ceil(viewport.height);await page.render({canvasContext:canvas.getContext('2d',{alpha:false}),viewport}).promise;return canvas}
function cropLowerRight(source){const sx=Math.floor(source.width*.48),sy=Math.floor(source.height*.48),sw=source.width-sx,sh=source.height-sy;const out=document.createElement('canvas');out.width=sw;out.height=sh;const ctx=out.getContext('2d',{alpha:false});ctx.filter='grayscale(1) contrast(1.35)';ctx.drawImage(source,sx,sy,sw,sh,0,0,sw,sh);return out}
async function ocrCanvas(canvas,onProgress,label){if(!globalThis.Tesseract)throw new Error('Tesseract.js não carregado.');const result=await Tesseract.recognize(canvas,'por+eng',{logger:m=>{if(m.status==='recognizing text')onProgress?.({stage:'ocr',label,progress:m.progress||0})}});return String(result?.data?.text||'')}
export async function extractPdfMetadata(file,{onProgress}={}){const{pdf,text,lines}=await textFromPdf(file,onProgress);let fields=parseExtractedText(text,lines),source='pdf-text';const weak=text.replace(/\s/g,'').length<MIN_TEXT_CHARS||Object.values(fields).some(f=>!f.value||f.confidence<AUTO_THRESHOLD||f.ambiguous);if(weak){onProgress?.({stage:'ocr-start'});const canvas=await renderPageCanvas(pdf,1,1.8);const zoneText=await ocrCanvas(cropLowerRight(canvas),onProgress,'carimbo');const zone=parseExtractedText(zoneText,zoneText.split(/\r?\n/).map(clean).filter(Boolean));fields={code:mergeField(fields.code,zone.code),title:mergeField(fields.title,zone.title),revision:mergeField(fields.revision,zone.revision)};source='pdf-text+ocr-zone';if(Object.values(fields).some(f=>!f.value||f.confidence<AUTO_THRESHOLD||f.ambiguous)){const fullText=await ocrCanvas(canvas,onProgress,'página inteira');const full=parseExtractedText(fullText,fullText.split(/\r?\n/).map(clean).filter(Boolean));fields={code:mergeField(fields.code,full.code),title:mergeField(fields.title,full.title),revision:mergeField(fields.revision,full.revision)};source='pdf-text+ocr'}}return resultFrom(fields,source)}
export async function processPdfBatch(files,{onFileProgress,onBatchProgress}={}){const list=[...files],results=[];for(let i=0;i<list.length;i++){const file=list[i];onBatchProgress?.({index:i,total:list.length,file});try{results.push({file,...await extractPdfMetadata(file,{onProgress:p=>onFileProgress?.({file,index:i,...p})})})}catch(error){results.push({file,extracted:{code:'',title:'',revision:''},confidence:{code:0,title:0,revision:0},issues:[error.message||'Falha ao processar PDF.'],source:'error',status:'review'})}}return results}
