import assert from'node:assert/strict';
import{readFile}from'node:fs/promises';
const read=path=>readFile(new URL(path,import.meta.url),'utf8');
const[catalogRepo,importer,localUx,nativeImporter,fileService,viewer,app,smoke,finalGates,documentsState,incremental,zipStream]=await Promise.all([read('../js/documents/catalog-repository.js'),read('../js/documents/package-import-service.js'),read('../js/local-documents-ux.js'),read('../native/android/NativePackageImporterPlugin.java'),read('../js/documents/file-service.js'),read('../js/documents/viewer-service.js'),read('../js/app.js'),read('./browser-smoke.mjs'),read('./browser-final-gates.mjs'),read('./browser-documents-state.mjs'),read('../js/documents/incremental-update.js'),read('../js/documents/zip-stream.js')]);
// Primeiro boot / login.
assert.match(catalogRepo,/does not exist/);assert.match(catalogRepo,/return null/);assert.match(app,/signIn|login|auth/i);assert.match(smoke,/login|auth|session/i);
// Um único seletor nativo; o ZIP não cruza o bridge JavaScript.
assert.match(importer,/usesNativePicker\(\)/);assert.match(importer,/NativePackageImporter\.importPackage\(\)/);assert.match(localUx,/const nativePicker=packageImportService\.usesNativePicker\(\)/);assert.match(localUx,/if\(!nativePicker&&!file\)/);assert.match(localUx,/nativePicker\?null:fileInput/);
// Android mantém acesso aleatório ao ZIP, mas remove a cópia extraída de cada PDF.
assert.match(nativeImporter,/copySelectedPackage\(uri,sourceZip\)|copySelectedPackage\(uri, sourceZip\)/);assert.match(nativeImporter,/new ZipFile\(sourceZip\)/);assert.doesNotMatch(nativeImporter,/new ZipInputStream/);assert.doesNotMatch(nativeImporter,/Base64|base64/);assert.match(nativeImporter,/BUFFER_SIZE=64\*1024|BUFFER_SIZE = 64 \* 1024/);assert.match(nativeImporter,/MAX_TOTAL_UNCOMPRESSED_BYTES/);assert.match(nativeImporter,/MIN_FREE_BYTES/);assert.match(nativeImporter,/indexEntries/);assert.match(nativeImporter,/parseJsonObject\(MANIFEST/);assert.match(nativeImporter,/parseJsonObject\(CATALOG/);assert.match(nativeImporter,/PDF vazio no pacote/);assert.doesNotMatch(nativeImporter,/stagedDocuments/);assert.match(nativeImporter,/archive\.getInputStream\(entry\)/);assert.match(nativeImporter,/MessageDigest\.getInstance\("SHA-256"\)/);
// Caminhos aninhados seguros continuam aceitos.
assert.match(nativeImporter,/String normalized=file\.replace\('\\\\','\/'\)|String normalized = file\.replace\('\\\\', '\/'\)/);assert.match(nativeImporter,/String\[\] parts\s*=\s*normalized\.split\("\/",\s*-1\)/);assert.match(nativeImporter,/"\.\."\.equals\(part\)/);assert.doesNotMatch(nativeImporter,/file\.contains\("\/"\) \|\| file\.contains/);assert.match(nativeImporter,/safeChild/);
const fixture='3-e-4-trilhos/DE-17.00.00.00-6P5-1301-0.pdf',segments=fixture.replace(/\\/g,'/').split('/');assert.deepEqual(segments,['3-e-4-trilhos','DE-17.00.00.00-6P5-1301-0.pdf']);assert.ok(segments.every(p=>p&&p!=='.'&&p!=='..'));assert.ok(fixture.toLowerCase().endsWith('.pdf'));
// Incremental: identidade, revisão, integridade e preservação do restante.
assert.match(nativeImporter,/"incremental"/);assert.match(nativeImporter,/buildPlan/);assert.match(nativeImporter,/compareRevision/);assert.match(nativeImporter,/identityKey/);assert.match(nativeImporter,/Revisão regressiva/);assert.match(nativeImporter,/Conflito de integridade/);assert.match(nativeImporter,/preserveInstalledFile/);assert.match(incremental,/createCatalogImportPlan/);assert.match(incremental,/removedFileIds/);
// Transação: arquivos novos são exclusivos e removidos se catálogo não for ativado; órfãos só saem após commit.
assert.match(nativeImporter,/packageVersion\s*\+\s*"__"\s*\+\s*runId/);assert.match(nativeImporter,/promotedThisRun/);assert.match(nativeImporter,/catalogCommitted/);assert.match(nativeImporter,/writeAtomically\(catalogTarget/);assert.match(nativeImporter,/cleanupUnreferencedFiles/);assert.match(nativeImporter,/deleteRecursively\(stagingRoot\)/);
// PWA: diretório central + OPFS, sem remontar PDFs inteiros.
assert.match(importer,/readZipDirectory/);assert.match(importer,/streamZipEntry/);assert.match(fileService,/supportsStreamingWeb/);assert.match(fileService,/navigator\.storage\?\.getDirectory/);assert.match(fileService,/createWritable/);assert.match(fileService,/rollbackPreparedRecords/);assert.match(zipStream,/file\.slice\(/);assert.doesNotMatch(importer,/concat\(|chunks\.push\(data\)/);
// Viewer Android continua sem Base64 na abertura.
assert.match(fileService,/async getViewerSource\(/);assert.match(fileService,/Filesystem\.getUri/);assert.match(fileService,/Capacitor\.convertFileSrc/);assert.match(viewer,/documentFileService\.getViewerSource\(doc\)/);assert.match(viewer,/getDocument\(\{url:source\.url\}\)/);assert.match(viewer,/if\(!blob\)blob=await documentFileService\.getBlob\(doc\)/);assert.match(viewer,/MAX_RENDER_PIXELS/);
// Navegação e visual permanecem cobertos.
assert.match(documentsState,/143|paginação|pagination/i);assert.match(finalGates,/mobile|tablet|desktop|viewport/i);
console.log('BYD Skyrail: contratos sistêmicos Android/PWA V1.1 validados.');
