import assert from'node:assert/strict';
import{readFile}from'node:fs/promises';
const read=path=>readFile(new URL(path,import.meta.url),'utf8');
const[catalogRepo,fileService,db,sync,importer,viewer,catalog,capacitor,netlify,localUx,localCss,packager,packagerUx,index,nativeImporter,androidPatch,packageJson,zipStream,incremental,sha256]=await Promise.all([
 read('../js/documents/catalog-repository.js'),read('../js/documents/file-service.js'),read('../js/db.js'),read('../js/sync.js'),read('../js/documents/package-import-service.js'),read('../js/documents/viewer-service.js'),read('../documents.json'),read('../capacitor.config.json'),read('../netlify.toml'),read('../js/local-documents-ux.js'),read('../local-documents.css'),read('../js/documents/document-packager-service.js'),read('../js/document-packager-ux.js'),read('../index.html'),read('../native/android/NativePackageImporterPlugin.java'),read('../scripts/patch-android-native-importer.mjs'),read('../package.json'),read('../js/documents/zip-stream.js'),read('../js/documents/incremental-update.js'),read('../js/documents/sha256-stream.js')
]);
const parsed=JSON.parse(catalog);assert.equal(parsed.schemaVersion,1);assert.ok(Array.isArray(parsed.documents));assert.ok(Array.isArray(parsed.systems));
assert.match(catalogRepo,/catalogVersion/);assert.match(catalogRepo,/generatedAt/);assert.match(catalogRepo,/documentCount/);assert.match(catalogRepo,/codeN === qCode/);assert.match(catalogRepo,/documentById = new Map/);assert.match(catalogRepo,/documentById\.get\(String\(id\)\)/);assert.match(catalogRepo,/function isMissingNativeFileError\(error\)/);assert.match(catalogRepo,/code === 'ENOENT'/);assert.match(catalogRepo,/message\.includes\('not found'\)/);assert.match(catalogRepo,/message\.includes\('does not exist'\)/);assert.match(catalogRepo,/message\.includes\('no such file'\)/);assert.match(catalogRepo,/if \(isMissingNativeFileError\(error\)\) return null;/);
assert.match(fileService,/Directory\.Data/);assert.doesNotMatch(fileService,/Directory\.Documents|Directory\.External/);assert.match(fileService,/getKey\(document\.id\)/);assert.match(fileService,/getAllKeys\(\)/);assert.match(fileService,/async availableIds\(/);assert.match(fileService,/async getViewerSource\(/);assert.match(fileService,/Filesystem\.getUri/);assert.match(fileService,/Capacitor\.convertFileSrc/);
assert.match(fileService,/navigator\.storage\?\.getDirectory/,'PWA deve detectar OPFS para escrita streaming');assert.match(fileService,/createWritable/,'PWA deve gravar PDF diretamente no armazenamento privado');assert.match(fileService,/maxBufferedBytes/,'fallback sem OPFS deve possuir teto explícito de RAM');assert.match(fileService,/commitPreparedRecords/);assert.match(fileService,/rollbackPreparedRecords/);
assert.match(db,/availabilityPromise/);assert.match(db,/documentFileService\.availableIds\(docs\)/);assert.doesNotMatch(sync,/docs\.forEach\(/);
assert.match(importer,/Pacote incompatível/);assert.match(importer,/Pacote incompleto/);assert.match(importer,/Importação interrompida sem substituir o catálogo ativo/);assert.match(importer,/readZipDirectory/,'fallback web deve ler diretório central sem materializar ZIP inteiro');assert.match(importer,/streamZipEntry/,'PDF web deve fluir do ZIP para armazenamento');assert.match(importer,/supportsStreamingWeb/);assert.doesNotMatch(importer,/concat\(|chunks\.push\(data\)/,'importador não deve remontar cada PDF completo antes de gravar');assert.match(importer,/registerPlugin\('NativePackageImporter'\)/);assert.match(importer,/usesNativePicker\(\)/);assert.match(importer,/NativePackageImporter\.importPackage\(\)/);assert.match(importer,/documentRepository\.load\(\{force:true\}\)/);
assert.match(localUx,/const nativePicker=packageImportService\.usesNativePicker\(\)/);assert.match(localUx,/if\(!nativePicker&&!file\)/);
assert.match(nativeImporter,/new ZipFile\(sourceZip\)/);assert.match(nativeImporter,/BufferedOutputStream/);assert.doesNotMatch(nativeImporter,/Base64|base64/);assert.doesNotMatch(nativeImporter,/byte\[\]\s+.*=.*new byte\[\(int\)/);assert.match(nativeImporter,/MAX_METADATA_BYTES/);assert.match(nativeImporter,/MAX_TOTAL_UNCOMPRESSED_BYTES/);assert.match(nativeImporter,/MIN_FREE_BYTES/);assert.match(nativeImporter,/indexEntries/,'ZIP deve rejeitar entradas duplicadas durante indexação');assert.match(nativeImporter,/normalizeEntryName/);assert.match(nativeImporter,/safeChild/);assert.match(nativeImporter,/writeAtomically/);assert.match(nativeImporter,/packageVersion\s*\+\s*"__"\s*\+\s*runId/);assert.match(nativeImporter,/promotedThisRun/);assert.match(nativeImporter,/cleanupUnreferencedFiles/);assert.match(nativeImporter,/staging-native/);assert.match(nativeImporter,/deleteRecursively\(stagingRoot\)/);
assert.match(nativeImporter,/MessageDigest\.getInstance\("SHA-256"\)/,'Android deve calcular SHA-256 no fluxo de gravação');assert.match(nativeImporter,/archive\.getInputStream\(entry\)/,'Android deve descompactar diretamente da entrada ZIP para o destino transacional');assert.doesNotMatch(nativeImporter,/stagedDocuments/,'Android V1.1 não deve criar uma segunda cópia extraída de todos os PDFs');assert.match(nativeImporter,/incremental/);assert.match(nativeImporter,/compareRevision/);assert.match(nativeImporter,/Conflito de integridade/);assert.match(nativeImporter,/Revisão regressiva/);
assert.match(packager,/packagedFile:`\$\{slug\(result\.record\.system\|\|'Sem sistema'\)\}\/\$\{entry\.fileName\}`/);assert.match(nativeImporter,/String\[\] parts\s*=\s*normalized\.split\("\/",\s*-1\)/);assert.match(nativeImporter,/"\.\."\.equals\(part\)/);assert.doesNotMatch(nativeImporter,/file\.contains\("\/"\) \|\| file\.contains/);assert.match(androidPatch,/registerPlugin\(NativePackageImporterPlugin\.class\)/);assert.match(packageJson,/"android:patch"/);
assert.doesNotMatch(packager,/unzipSync|zipSync/);assert.doesNotMatch(packager,/pdfZipFile\.arrayBuffer/);assert.match(packager,/readZipDirectory/);assert.match(zipStream,/file\.slice\(/,'leitor ZIP compartilhado deve consultar apenas regiões necessárias');assert.match(packager,/showSaveFilePicker/);assert.match(packager,/new ZipPassThrough/);assert.match(packager,/AbortError/);assert.match(packager,/missingMaster/);assert.match(packager,/duplicateFileNames/);assert.match(packager,/schemaVersion:2/);assert.match(packager,/hashAlgorithm:'SHA-256'/);assert.match(packager,/mode:packageMode/);assert.match(packagerUx,/Validar arquivos/);assert.match(packagerUx,/Gerar pacote no disco/);assert.match(packagerUx,/data-packager-cancel/);assert.match(packagerUx,/data-packager-mode/);assert.match(packagerUx,/Atualização incremental/);assert.match(index,/packager\.css/);
assert.match(incremental,/createCatalogImportPlan/);assert.match(incremental,/compareDocumentRevisions/);assert.match(incremental,/Revisão regressiva/);assert.match(incremental,/mesma revisão possui SHA-256 diferente/);assert.match(sha256,/class Sha256Stream/);
assert.match(viewer,/canvas/);assert.match(viewer,/pdf\.numPages/);assert.match(viewer,/pointerdown/);assert.match(viewer,/pinchStart/);assert.match(viewer,/scrollLeft/);assert.match(viewer,/requestFullscreen/);assert.match(viewer,/documentFileService\.getViewerSource\(doc\)/);assert.match(viewer,/getDocument\(\{url:source\.url\}\)/);assert.match(viewer,/devicePixelRatio/);assert.match(viewer,/MAX_RENDER_PIXELS/);assert.match(viewer,/renderDensity\(/);assert.match(viewer,/canvas\.style\.width/);assert.match(viewer,/availableWidth\/base\.width/);assert.match(viewer,/Ajustar ·/);assert.match(viewer,/title="\$\{esc\(title\)\}"/);assert.match(viewer,/viewerIcon\('download'\)/);assert.match(viewer,/viewerIcon\('fullscreen'\)/);assert.match(viewer,/viewerIcon\('close'\)/);assert.match(viewer,/data-pdf-canvas hidden/);assert.match(viewer,/stage\.classList\.remove\('is-loading'\)/);assert.match(localCss,/canvas\[hidden\]\{display:none\}/);assert.match(localCss,/Renderizando documento/);assert.doesNotMatch(viewer,/local-pdf-controls-hidden/);assert.match(localCss,/\.local-pdf-toolbar\{position:relative/);assert.doesNotMatch(localCss,/\.local-pdf-toolbar\{position:absolute/);assert.match(localCss,/white-space:normal/);
assert.match(localUx,/master-approved/);assert.match(localUx,/master-nonconforming/);assert.match(localUx,/master-analysis/);assert.match(localUx,/master-not-approved/);assert.match(localUx,/PAGE_SIZE=100/);assert.match(localUx,/documentsMedia\.matches/);assert.match(localCss,/touch-action:none/);assert.match(localCss,/#00b050/);assert.match(localCss,/#ea9999/);assert.match(localCss,/#fef2cb/);assert.match(localCss,/#ff0000/);assert.match(localCss,/\.mobile-doc-top\{display:grid;grid-template-columns:minmax\(0,1fr\) auto/);assert.match(localCss,/\.mobile-doc-top \.doc-code\{display:block;min-width:0;max-width:100%;overflow-wrap:anywhere/);assert.match(localCss,/\.local-filter-grid select,.local-document-search-panel \.input-control\{width:100%\}/);assert.match(localCss,/\.mobile-doc-meta>\*\{min-width:0;max-width:100%\}/);assert.match(capacitor,/"appName": "BYD Skyrail"/);assert.match(netlify,/publish = "dist"/);
console.log('BYD Skyrail: contratos do módulo documental local V1.1 validados.');
