import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { fileChanged, matchesDocument, normalizeDocument } from '../js/model.js';
import { parseExtractedText } from '../js/bulk-import.js';

const systemId='11111111-1111-4111-8111-111111111111';
const base={id:'00000000-0000-4000-8000-000000000001',code:'TEST-001',title:'Documento',discipline:'Civil',system_id:systemId,revision:'A',file_path:'id/a.pdf',updated_at:'2026-08-21T00:00:00Z',active:true};
assert.equal(normalizeDocument(base)?.code,'TEST-001');assert.equal(normalizeDocument(base)?.system_id,systemId);assert.equal(matchesDocument(base,{query:'documento'}),true);assert.equal(matchesDocument(base,{systemId}),true);assert.equal(matchesDocument(base,{systemId:'22222222-2222-4222-8222-222222222222'}),false);assert.equal(fileChanged(base,{...base,revision:'B'}),true);
const parsed=parseExtractedText('CÓDIGO: PW-L17-ABC-001\nDESCRIÇÃO: Planta geral da via permanente\nREVISÃO: H');assert.equal(parsed.code.value,'PW-L17-ABC-001');assert.equal(parsed.title.value,'Planta geral da via permanente');assert.equal(parsed.revision.value,'H');
const ambiguous=parseExtractedText('PW-L17-001 PW-L17-002\nREV: A\nDESCRIÇÃO: Documento de teste');assert.equal(ambiguous.code.ambiguous,true);

const paths=['../js/api.js','../js/db.js','../js/sync.js','../js/app.js','../js/systems-ux.js','../js/ux-adjustments.js','../js/bulk-import.js','../js/bulk-import-ui.js','../styles.css','../ux-adjustments.css','../systems.css','../bulk-import.css','../index.html','../manifest.webmanifest','../sw.js','../supabase/migrations/20260821154420_initial_byd_skyrail_schema.sql','../supabase/migrations/20260821173500_add_governance_and_document_history.sql','../supabase/migrations/20260821174500_move_admin_helper_to_private_schema.sql','../supabase/migrations/20260821175500_optimize_governance_policies.sql','../supabase/migrations/20260824114348_add_systems_entity.sql'];
const files=await Promise.all(paths.map(p=>readFile(new URL(p,import.meta.url),'utf8')));const [api,db,sync,app,systemsUx,uxJs,bulk,bulkUi,styles,uxCss,systemsCss,bulkCss,index,manifest,sw,initialMigration,governanceMigration,privateAuthMigration,performanceMigration,systemsMigration]=files;const source=files.join('\n').toLowerCase();assert.doesNotMatch(source,/docinspector_|sky17_|service_role|servicerole|secretkey/);
assert.match(api,/listSystems/);assert.match(api,/saveSystem/);assert.match(api,/system_id/);assert.match(db,/const META='documents';const FILES='files'/);assert.match(sync,/f\.blob\.slice\(0,5\)\.arrayBuffer/);assert.match(sw,/const VERSION='1\.1\.6'/);assert.match(sw,/bulk-import\.js/);assert.match(sw,/bulk-import-ui\.js/);assert.doesNotMatch(sw,/l17-ouro-hero\.svg/);
assert.match(app,/routeFromHash/);assert.match(app,/Conferência \/ Auditoria/);assert.match(systemsUx,/#\/documents\?system=/);assert.match(systemsUx,/Todos os sistemas/);assert.match(systemsCss,/systems-card-grid/);
assert.match(bulk,/getTextContent/);assert.match(bulk,/groupLines/);assert.match(bulk,/CODE_RE/);assert.match(bulk,/REV_LABEL_RE/);assert.match(bulk,/DESC_LABEL_RE/);assert.match(bulk,/cropLowerRight/);assert.match(bulk,/Tesseract\.recognize/);assert.match(bulk,/status:issues\.length\?'review':'ready'/);
assert.match(bulkUi,/data-new-doc/);assert.match(bulkUi,/data-bulk-import/);assert.match(bulkUi,/pdf\.min\.js/);assert.match(bulkUi,/tesseract\.js@5\.1\.1/);assert.match(bulkUi,/multiple required/);assert.match(bulkUi,/Revisão necessária/);assert.match(bulkUi,/Confirmar e salvar lote/);assert.match(bulkUi,/system_id/);assert.match(bulkUi,/saveDocument/);assert.match(bulkCss,/bulk-table/);assert.match(index,/bulk-import\.css/);assert.match(index,/bulk-import-ui\.js/);
assert.match(uxCss,/\.hero-rail\{display:none!important;background:none!important/);assert.doesNotMatch(uxCss,/l17-ouro-hero\.svg/);assert.match(styles,/@media \(max-width:767px\)/);assert.match(manifest,/"start_url": "\.\/#\/home"/);
assert.match(initialMigration,/create table public\.documents/i);assert.match(governanceMigration,/create table if not exists public\.document_history/i);assert.match(privateAuthMigration,/private\.is_active_admin/i);assert.match(performanceMigration,/members_read_self_or_admin/i);assert.match(systemsMigration,/create table if not exists public\.systems/i);assert.match(systemsMigration,/add column if not exists system_id uuid null/i);
console.log('BYD Skyrail: UX, sistemas e importação em massa com revisão humana validados.');
